<a href="https://colab.research.google.com/github/JennEYoon/Coursera-DLAI/blob/main/numpy4_struct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Quick Practice, numpy4, structured array  

In [1]:
# numpy4, quick practice  
# Structured Arrays in numpy  
# Data start Jan 18, 2022 1:30 pm, 3:10 pm stopped
# Github repo: "code" folder "current" file "numpy4_structured.py"  

import numpy as np 
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [2]:
# Structured Array data type  
# Only data type that can have strings in a numpy cell.
            
data = {'person':['Mary', "Jisoo", "Kevin", "Craig"], 
        'weight':[125.5, 105.3, 163.2, 180.9], 
        'id':[101, 102, 55, 56]}
print(data, type(data))

{'person': ['Mary', 'Jisoo', 'Kevin', 'Craig'], 'weight': [125.5, 105.3, 163.2, 180.9], 'id': [101, 102, 55, 56]} <class 'dict'>


In [9]:
# mat = np.structured(data=data, dtype={'person': 'string', 'age':'float16', 'id':'uint'})     
# Not sure about name of function for structured array  
# Not sure about format      

# First create an empty container with compound data types
# Then fill with data, each item is a list.

tp = np.dtype=({'names':('person', 'weight', 'id'), 'formats':('U10', 'f8', 'u1')})
# each items are tuples, so ( ) and not list [ ]
X = np.zeros(4, dtype=tp) 
# 4 rows, each with 3 columns  
print(X, type(X), '\n')

X['person'] = data['person']
X['weight'] = data['weight']
X['id'] = data['id']
print(X, type(X), '\n')

print("4th record: ", X[3], "Name: ", X[3]['person'])

[('', 0., 0) ('', 0., 0) ('', 0., 0) ('', 0., 0)] <class 'numpy.ndarray'> 

[('Mary', 125.5, 101) ('Jisoo', 105.3, 102) ('Kevin', 163.2,  55)
 ('Craig', 180.9,  56)] <class 'numpy.ndarray'> 

4th record:  ('Craig', 180.9, 56) Name:  Craig


In [10]:
# Try in one go  

Y = np.array(data, dtype=tp)
print(Y, type(Y))

TypeError: ignored

In [6]:
A = np.ones((3, 5), dtype='float32')
# expect 3 row x 5 col matrix of floating point 1.'s.  
print("ones: \n", A, type(A), '\n')

# B = np.random.random((3, 5), dtype='float16') 
# expect 3 row x 5 col matrix, random numbers (0, 1) uniform distribution  
# no type attribute for random generator. Returns float always. 
#  B = np.random.random(3,5) # row x col needs to be a single object, inside ().
B = np.random.random((3, 5))
print("randome: \n", B, type(B), '\n')

# C = np.random.normal((3, 3), (0, 3))      
# expect 3 x 3 matric, random numbers from (mu=0, sigma=+/- 3) normal distribution  
# ex: np.random.normal(3, 2.5, size=(2, 4))
# np.random.normal(mu, sigma, size=(row, col))

C = np.random.normal(0, 6, size=(3, 5))
print("normal dist: \n", C, type(C))

ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'> 

randome: 
 [[0.44632342 0.84276813 0.73352337 0.29567356 0.97470118]
 [0.81850204 0.05012834 0.53188638 0.27503883 0.47992288]
 [0.02773202 0.8420347  0.80172319 0.38064405 0.19458141]] <class 'numpy.ndarray'> 

normal dist: 
 [[ 3.03584202  6.68102199  0.50757737 10.51488636  1.15349373]
 [-5.37782317 -1.07619403  4.8113455   1.4982354  -1.95052267]
 [-0.87600221  0.56925171  1.40976336  3.71878832  7.02800969]] <class 'numpy.ndarray'>


In [7]:
# random with reshape  
R = np.random.random(16)
R


array([0.74619932, 0.51854679, 0.25737467, 0.80019657, 0.44731683,
       0.40264002, 0.52102866, 0.453735  , 0.68414209, 0.35433349,
       0.32457585, 0.81593403, 0.83904114, 0.49573734, 0.815308  ,
       0.84018949])

In [10]:
R2 = np.random.randint(-10, 10, 16)
R3 = R2.reshape(2, 8)
R3

array([[ 2, -9,  8,  2,  7, -7,  8, -2],
       [ 8, -3,  5, -7, -3,  1,  1,  3]])